### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by B1GGUN** [MangoWAY/SMIBID_BrainRegistration#1]
Thanks for sharing, but how to augment the dataset with only one private dataset (60 MRI images with labels)? Which part needs to be modified?

**Comment by MangoWAY** [comment]
You can see the `Demo.py`, the file shows two cases:
- Use a given brain mask to generate synthetic volume data.
- Sample a DVF (deformation vector field) from the trained 3d-VAE model, and use the DVF to deform the volume data.

The generation function is in the `imageGenerator.py` and `DVFGenerator.py` and you can see the comments in these files to figure out how to use it.

**Comment by B1GGUN** [comment]
thanks
